version: '3.7'

services:
    test-mysql:
        image: mysql:latest
        container_name: test-mysql
        restart: always
        environment:
            MYSQL_DATABASE: test
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306

    backend:
        build:
            context: .
            dockerfile: dockerfile
        container_name: backend
        volumes:
            - ./src:/backend/src
            - ./prisma:/backend/prisma
        depends_on:
            - test-mysql
        env_file:
            - .env
        ports:
            - 7000:7000

volumes:
    backend:
    mysql:
